load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "piet_run",
    srcs = [
        "piet_run.cpp"
    ],
    deps = [
        "//lib:piet_lib"
    ],
    visibility = ["//visibility:public"]
)